# Generated by Django 5.2 on 2025-07-12 05:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahuf_app', '0001_initial'),
        ('OAhuf_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='OCart', to='OAhuf_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='OCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocart_items', to='Ahuf_app.cart')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OAhuf_items', to='Ahuf_app.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='OutletCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='OAhuf_app.booking')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_id', to='Ahuf_app.menuitem')),
            ],
            options={
                'unique_together': {('booking', 'menu_item')},
            },
        ),
    ]
