# Generated by Django 5.2 on 2025-07-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAhuf_app', '0002_ocart_ocartitem_outletcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cust_identifier',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
