# Generated by Django 5.2 on 2025-07-12 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OAhuf_app', '0003_booking_cust_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cust_identifier',
        ),
    ]
