# Generated by Django 5.2 on 2025-07-12 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAhuf_app', '0004_remove_booking_cust_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator('^Cust_\\+?\\d{10,15}$|^Cust_[a-zA-Z0-9]{8}$')]),
        ),
    ]
