# Generated by Django 5.2 on 2025-07-12 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAhuf_app', '0005_alter_booking_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator(message="Mobile number must start with 'Cust_'", regex='^Cust_')]),
        ),
    ]
