# Generated by Django 5.2 on 2025-07-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAhuf_app', '0010_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='bills/'),
        ),
    ]
