# Generated by Django 5.2 on 2025-07-17 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAhuf_app', '0012_remove_outletcart_added_on_outletcart_portion_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletcart',
            name='added_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='outletcart',
            name='portion_size',
            field=models.CharField(choices=[('half', 'Half'), ('full', 'Full')], default='full', max_length=10),
        ),
    ]
