# Generated by Django 5.2 on 2025-07-12 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAhuf_app', '0006_alter_booking_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$')]),
        ),
    ]
