# Generated by Django 5.2 on 2025-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAhuf_app', '0011_bill_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletcart',
            name='added_on',
        ),
        migrations.AddField(
            model_name='outletcart',
            name='portion_size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
