# Generated by Django 5.2 on 2025-07-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAhuf_app', '0014_rename_portion_size_outletcart_plate_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outletcart',
            name='plate_size',
            field=models.CharField(default='full', max_length=10),
        ),
    ]
