# Generated by Django 5.2 on 2025-07-17 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahuf_app', '0002_alter_cartitem_unique_together_cartitem_plate_option_and_more'),
        ('OAhuf_app', '0015_alter_outletcart_plate_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outletcart',
            name='plate_size',
        ),
        migrations.AddField(
            model_name='outletcart',
            name='plate_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ahuf_app.plateoption'),
        ),
    ]
