# Generated by Django 5.2 on 2025-07-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAhuf_app', '0016_remove_outletcart_plate_size_outletcart_plate_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
