# Generated by Django 5.2 on 2025-07-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OAhuf_app', '0017_booking_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletcart',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
