# Generated by Django 5.2 on 2025-07-17 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ahuf_app', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='plate_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ahuf_app.plateoption'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Ahuf_app.cart'),
        ),
        migrations.AlterField(
            model_name='combomenu',
            name='for_catering',
            field=models.BooleanField(default=False, help_text='Is this combo available for catering? Make sure its category also in catering.'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plateoption',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plateoption',
            name='plate_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'content_type', 'object_id', 'plate_option')},
        ),
    ]
